name: ci

on:
  push:
    branches:
    - dev
    tags:
      - '*.*.*'

jobs:
  prepare:
    name: Run CI
    runs-on:
      group: kroma-runners
      labels: kroma-ubuntu-22-04-16core

    outputs:
      kroma-node: ${{ steps.packages.outputs.kroma-node }}
      kroma-validator: ${{ steps.packages.outputs.kroma-validator }}
      kroma-batcher: ${{ steps.packages.outputs.kroma-batcher }}
      kroma-stateviz: ${{ steps.packages.outputs.kroma-stateviz }}
      docker-tag: ${{ steps.docker-image-name.outputs.docker-tag }}

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - run: go mod download

      - name: Setup Node.js 16.x
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn Cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-e15e33a07c0920189fc336391f538c3dad53da73

      - name: Build
        run: yarn build

      - name: Run Tests
        env:
          E2E_DISABLE_PARALLEL: true
        run: make test

      - name: Docker Image Name
        id: docker-image-name
        run: |
          if [[ $GITHUB_REF_TYPE == 'branch' ]];
          then
            echo "docker-tag=dev-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT
          else
            echo "docker-tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

  kroma-node:
    name: Kroma Node Version ${{ needs.prepare.outputs.docker-tag }}
    needs: prepare
    runs-on:
      group: kroma-runners
      labels: kroma-ubuntu-22-04-16core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Publish kroma Node
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64
          target: kroma-node
          push: true
          tags: kromanetwork/node:${{ needs.prepare.outputs.docker-tag }}

  kroma-validator:
    name: Kroma Validator Version ${{ needs.prepare.outputs.docker-tag }}
    needs: prepare
    runs-on:
      group: kroma-runners
      labels: kroma-ubuntu-22-04-16core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Publish kroma Node
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64
          target: kroma-validator
          push: true
          tags: kromanetwork/validator:${{ needs.prepare.outputs.docker-tag }}

  kroma-batcher:
    name: Kroma Batcher Version ${{ needs.prepare.outputs.docker-tag }}
    needs: prepare
    runs-on:
      group: kroma-runners
      labels: kroma-ubuntu-22-04-16core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Publish kroma Node
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64
          target: kroma-batcher
          push: true
          tags: kromanetwork/batcher:${{ needs.prepare.outputs.docker-tag }}


