name: Tests

on:
  pull_request:
    branches:
    - dev
    - main

jobs:
  test:
    name: Run tests
    runs-on:
      group: kroma-runners
      labels: kroma-ubuntu-22-04-16core
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - run: go mod download

      - name: Setup Node.js 16.x
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn Cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-e15e33a07c0920189fc336391f538c3dad53da73

      - name: Build
        run: yarn build

      - name: Run tests
        env:
          E2E_DISABLE_PARALLEL: true
        run: make test
